portal:
  base_url: "https://www.google.com"
  headers:
    cookie: ""

mysql:
  host: "localhost"
  port: 3306
  user: ""
  password: ""
  database: ""

redis:
  host: "localhost"
  port: 6379
  password: ""
  db: 0

clickhouse:
  host: "localhost"
  port: 9000
  user: ""
  password: ""
  database: ""

ssh:
  ssh_host: ""
  ssh_port: 22
  ssh_user: ""
  ssh_key: ""
  ssh_password: ""

driver_ip: "1.2.3.4"

forwarder_servers:
  - "1.1.1.1:1111"
  - "2.2.2.2:2222"

kafka_consumer:
  sasl.username: ""
  sasl.password: ""
  sasl.mechanism: "PLAIN"
  security.protocol: "SASL_PLAINTEXT"
  group.id: ""
  topic.name: ""

locust:
  uri: "/about"
  method: "get"
  min_wait: 1
  max_wait: 2
  users: 10
  spawn_rate: 1
  num_requests: ""
  run_time: "1m"
