portal:
  base_url: https://www.google.com
  headers:
    cookie: null

mysql:
  host: localhost
  port: 3306
  user: null
  password: null
  database: null

redis:
  host: localhost
  port: 6379
  password: null
  db: 0

clickhouse:
  host: localhost
  port: 9000
  user: null
  password: null
  database: null

ssh:
  ssh_host: null
  ssh_port: 22
  ssh_user: null
  ssh_key: /Users/null/.ssh/id_rsa
  ssh_password: null

email:
  sender: null 
  password: null 
  server: null 
  recipients: null

driver_ip: 1.2.3.4
