email:
  sender: ""
  password: ""
  server: ""
  recipients: ""

message:
  account_sid: ""
  auth_token: ""
  from: ""
  to: ""

google_api:
  google_drive:
    folder_name: ""
  google_email:
    default_recipient: ""
  google_sheet:
    file_name: ""
    sheet_name: ""

chat_bot:
  api_key: ""
  base_url: "https://api.openai.com/v1"
  model: ""
  history: 0
